### ISSUE TITLE
Short-term roadmap for this implementation 

### ISSUE THREAD

**Issue by waynexia** [datafusion-contrib/orc-rust#34]
Previous discussion: https://github.com/apache/arrow-datafusion/issues/4707

Though the ORC format is not as widely used as parquet in arrow-rs and datafusion related projects, there are still some (growing, to my feelings) interesting and requirements on this format. As @Jefffrey said [here](https://github.com/apache/arrow-datafusion/issues/4707#issuecomment-1792031298), a noticeable and viable milestone for this project is it can be merged into arrow-rs. This draft roadmap is raised to help us discuss, arrange and take our efforts toward that milestone.

Given the ORC format is less complex than parquet, there are still many work to do in various aspects. Here is a list of functionalities need to be done if we consider making ORC files queriable from datafusion as the primary use case on this stage. Please feel free to add/remove/set priorities to them. It's likely that we can't finish all of them in a short term, thus marking what are going to be done is also important.

- [x] primitive data types (ORC [refs](https://orc.apache.org/docs/types.html))
  - [x] tiny int https://github.com/datafusion-contrib/datafusion-orc/issues/22
  - [x] timestamp with local time zone https://github.com/datafusion-contrib/datafusion-orc/issues/13
  - [x] decimal https://github.com/datafusion-contrib/datafusion-orc/issues/18
- [x] common compress methods https://github.com/datafusion-contrib/datafusion-orc/issues/10
- [x] user metadata
- [x] other encodings https://github.com/datafusion-contrib/datafusion-orc/pull/24
- [ ] Benchmark https://github.com/datafusion-contrib/datafusion-orc/issues/8

The below are also related but with lower priorities
- [x] compound data types https://github.com/datafusion-contrib/datafusion-orc/issues/14
  - [x] struct https://github.com/datafusion-contrib/datafusion-orc/pull/26
  - [x] list
  - [x] map
  - [x] union
- [ ] file metadata and statistics
- [ ] pruning https://github.com/datafusion-contrib/orc-rust/issues/17

Long term items:
- [ ] encryption

~~Then something I'm not sure about. Looking for more information. Also feel free to change previous two lists.~~
